# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.17-SNAPSHOT

# Dependencies
fabric_api_version=0.145.1+26.1

# Mod Properties
mod_version=1.6
maven_group=net.darktree
archives_base_name=JMXL

